### ISSUE TITLE
Manifest file for service discovery-enabled service

### ISSUE THREAD

**Issue by galer7** [donnieprakoso/copilot.rocks#1]
Hey @donnieprakoso, I stumbled across [your tutorial](https://www.copilot.rocks/implementing-architectural-patterns/10-service-discovery) about deploying apps on ECS using copilot, great stuff!

I was wondering if you could provide the manifest file for `app2` from [this step](https://www.copilot.rocks/implementing-architectural-patterns/10-service-discovery/#task-1-run-copilot-init) of the article, as I'm facing problems setting up service discovery between 2 of my services (a Flask one and a Postgres one).

I did create the service using the wizard, but the resulting manifest file looks like this (after I've added my env variables):

```
name: pgvector
type: Backend Service

image:
  location: ankane/pgvector

cpu: 256       # Number of CPU units for the task.
memory: 512    # Amount of memory in MiB used by the task.
count: 1       # Number of tasks that should be running in your service.
exec: true     # Enable running commands in your container.

# \/ ADDED BY ME \/
network:
  connect: true

variables:
  POSTGRES_USER: ...
  POSTGRES_PASSWORD: ...
  POSTGRES_DB: ...
```

The `connect: true` was added by me, as I've found in [the copilot docs](https://aws.github.io/copilot-cli/docs/developing/svc-to-svc-communication/#how-do-i-use-service-connect).
However, when I run `copilot svc show`, I do not get the service discovery section as you did in [this step](https://www.copilot.rocks/implementing-architectural-patterns/10-service-discovery/#task-3-get-app2-network-location).

Have a great weekend,
Gabriel
